### ISSUE TITLE
针对8.9.83版本的qq无效

### ISSUE THREAD

**Issue by Eeeextend** [fuqiuluo/TXHook#125]

**Comment by Eeeextend** [comment]
java.lang.ClassNotFoundException: Didn't find class "com.tencent.mobileqq.startup.step.LoadDex" on path: DexPathList[[zip file "/data/app/~~ZkCXlvStueTb_PZahRAJhw==/com.tencent.mobileqq-CmuyXCGyQU_fYxBEowd-sQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~ZkCXlvStueTb_PZahRAJhw==/com.tencent.mobileqq-CmuyXCGyQU_fYxBEowd-sQ==/lib/arm64, /data/app/~~ZkCXlvStueTb_PZahRAJhw==/com.tencent.mobileqq-CmuyXCGyQU_fYxBEowd-sQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at moe.ore.txhook.hook.StartupHook.doInit(StartupHook.kt:38)
                                                                                                    	at moe.ore.txhook.hook.HookEntry.handleLoadPackage(HookEntry.kt:18)
                                                                                                    	at ncJRC.wKZy.P.qJvh.V.mE.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
                                                                                                    	at ncJRC.wKZy.P.qJvh.V.mE.callbacks.XC_LoadPackage.call(Unknown Source:6)
                                                                                                    	at ncJRC.wKZy.P.qJvh.V.mE.callbacks.XCallback.callAll(Unknown Source:26)
                                                                                                    	at g0.a(Unknown Source:281)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at J.callback(Unknown Source:250)
                                                                                                    	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)

**Comment by Eeeextend** [comment]
qq 1938317929
